name: CI
on: [push]

jobs:
  validate:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate s3fs binary checksum
        run: cat SHASUM_256 | shasum -a 256 -c
